-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 21:48:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema all_connected_users
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `all_connected_users` ;

-- -----------------------------------------------------
-- Schema all_connected_users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `all_connected_users` DEFAULT CHARACTER SET utf8 ;
USE `all_connected_users` ;

-- -----------------------------------------------------
-- Table `all_connected_users`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_users`.`rol` ;

CREATE TABLE IF NOT EXISTS `all_connected_users`.`rol` (
  `id_rol` ENUM('admin', 'cm', 'event', 'organization', 'customer', 'supplier') NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_users`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_users`.`user` ;

CREATE TABLE IF NOT EXISTS `all_connected_users`.`user` (
  `id_user` VARCHAR(36) NOT NULL,
  `fullname` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `location_lat` DECIMAL(9,6) NULL,
  `location_lng` DECIMAL(9,6) NULL,
  `photo_url` VARCHAR(200) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_users`.`user_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_users`.`user_rol` ;

CREATE TABLE IF NOT EXISTS `all_connected_users`.`user_rol` (
  `id_user` VARCHAR(36) NOT NULL,
  `id_rol` ENUM('admin', 'cm', 'event', 'organization', 'customer', 'supplier') NOT NULL,
  PRIMARY KEY (`id_user`, `id_rol`),
  INDEX `fk_user_has_rol_rol1_idx` (`id_rol` ASC) VISIBLE,
  INDEX `fk_user_has_rol_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_rol_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `all_connected_users`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_rol_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `all_connected_users`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_users`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_users`.`organization` ;

CREATE TABLE IF NOT EXISTS `all_connected_users`.`organization` (
  `id_organization` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `location_lat` DECIMAL(9,6) NOT NULL,
  `location_lng` DECIMAL(9,6) NOT NULL,
  `photo_url` VARCHAR(200) NULL,
  PRIMARY KEY (`id_organization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_users`.`user_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_users`.`user_organization` ;

CREATE TABLE IF NOT EXISTS `all_connected_users`.`user_organization` (
  `id_organization` VARCHAR(36) NOT NULL,
  `id_user` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id_organization`, `id_user`),
  INDEX `fk_organization_has_user_user1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_organization_has_user_organization1_idx` (`id_organization` ASC) VISIBLE,
  CONSTRAINT `fk_organization_has_user_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `all_connected_users`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_has_user_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `all_connected_users`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
