-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 21:49:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema all_connected_business
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `all_connected_business` ;

-- -----------------------------------------------------
-- Schema all_connected_business
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `all_connected_business` DEFAULT CHARACTER SET utf8 ;
USE `all_connected_business` ;

-- -----------------------------------------------------
-- Table `all_connected_business`.`business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_business`.`business` ;

CREATE TABLE IF NOT EXISTS `all_connected_business`.`business` (
  `id_business` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `owner_id` VARCHAR(36) NOT NULL,
  `logo_url` VARCHAR(200) NULL,
  PRIMARY KEY (`id_business`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_business`.`business_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_business`.`business_member` ;

CREATE TABLE IF NOT EXISTS `all_connected_business`.`business_member` (
  `id_user` VARCHAR(45) NOT NULL,
  `id_business` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id_user`, `id_business`),
  CONSTRAINT `fk_business_member_business`
    FOREIGN KEY (`id_business`)
    REFERENCES `all_connected_business`.`business` (`id_business`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_business`.`business_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_business`.`business_organization` ;

CREATE TABLE IF NOT EXISTS `all_connected_business`.`business_organization` (
  `id_organization` VARCHAR(36) NOT NULL,
  `id_business` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id_organization`, `id_business`),
  CONSTRAINT `fk_business_organization_business1`
    FOREIGN KEY (`id_business`)
    REFERENCES `all_connected_business`.`business` (`id_business`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_business`.`suscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_business`.`suscription` ;

CREATE TABLE IF NOT EXISTS `all_connected_business`.`suscription` (
  `id_suscription` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price_month` FLOAT NOT NULL,
  `duration_months` INT NOT NULL,
  PRIMARY KEY (`id_suscription`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_business`.`suscription_benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_business`.`suscription_benefit` ;

CREATE TABLE IF NOT EXISTS `all_connected_business`.`suscription_benefit` (
  `id_benefit` INT NOT NULL AUTO_INCREMENT,
  `id_suscription` INT NOT NULL,
  `benefit` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_benefit`),
  INDEX `fk_suscription_benefit_suscription1_idx` (`id_suscription` ASC) VISIBLE,
  CONSTRAINT `fk_suscription_benefit_suscription1`
    FOREIGN KEY (`id_suscription`)
    REFERENCES `all_connected_business`.`suscription` (`id_suscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all_connected_business`.`business_suscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `all_connected_business`.`business_suscription` ;

CREATE TABLE IF NOT EXISTS `all_connected_business`.`business_suscription` (
  `id_business` VARCHAR(36) NOT NULL,
  `id_suscription` INT NOT NULL,
  `charge` FLOAT NOT NULL,
  `charge_date` DATETIME NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_business`, `id_suscription`),
  INDEX `fk_suscription_has_business_business1_idx` (`id_business` ASC) VISIBLE,
  INDEX `fk_suscription_has_business_suscription1_idx` (`id_suscription` ASC) VISIBLE,
  CONSTRAINT `fk_suscription_has_business_suscription1`
    FOREIGN KEY (`id_suscription`)
    REFERENCES `all_connected_business`.`suscription` (`id_suscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suscription_has_business_business1`
    FOREIGN KEY (`id_business`)
    REFERENCES `all_connected_business`.`business` (`id_business`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
